pid /tmp/nginx.pid;

http {
  types_hash_max_size 4096;
  ssl_certificate /etc/certificates/fullchain.pem;
  ssl_certificate_key /etc/certificates/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256;
  ssl_prefer_server_ciphers on;
  charset utf-8;
  http2 on;
  gzip on;
  include mime.types;
  map $scheme $hsts {
    https "max-age=63072000; includeSubDomains; preload";
  }
  include snippets/headers.conf;
  include snippets/csp.conf;
  sendfile on;
  tcp_nodelay on;
  tcp_nopush on;
  access_log off;
  error_log /dev/null;
  ssl_stapling on;
  ssl_stapling_verify on;
  client_max_body_size 0;
  proxy_read_timeout 600;
  proxy_send_timeout 600;
  resolver host.containers.internal;
  include /etc/nginx-sites/*;
  server {
    listen 80;
    listen [::]:80;
    return 301 https://$host$request_uri;
  }
  server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    location / {
      return 404;
    }
  }
}
events {
  worker_connections 1024;
}
