FROM fedora:44
RUN dnf up -y
RUN dnf install -y dovecot-pigeonhole
COPY dovecot.conf /etc/dovecot/dovecot.conf
COPY default.sieve /etc/dovecot/default.sieve
RUN sievec /etc/dovecot/default.sieve
CMD chown -Rh 1000:1000 /srv/mail && dovecot -F
