mail_uid = 1000
mail_gid = 1000
log_path = /dev/stdout
protocols = imap lmtp
mail_plugins = mail_crypt
ssl = required
ssl_min_protocol = TLSv1.3
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305
ssl_prefer_server_ciphers = yes
ssl_cert = </etc/certificates/fullchain.pem
ssl_key = </etc/certificates/privkey.pem
auth_username_format = %Ln
mail_home = /srv/mail/%Ln
passdb {
  driver = passwd-file
  args = scheme=ARGON2ID /etc/dovecot-local/users
  override_fields = userdb_mail_crypt_private_password=%{sha512:password}
}
service auth {
  inet_listener {
    port = 500
  }
}
service lmtp {
  inet_listener {
    port = 24
  }
}
protocol lmtp {
  mail_plugins = mail_crypt sieve
}
mail_location = maildir:~/mail
mail_attribute_dict = file:~/mail/attributes
plugin {
  mail_crypt_save_version = 2
  mail_crypt_curve = secp521r1
  mail_crypt_require_encrypted_user_key = true
  sieve_before = file:/etc/dovecot/default.sieve
  sieve_default = file:/tmp/local.sieve
}
namespace inbox {
  inbox = yes
  mailbox Junk {
    special_use = \Junk
    auto = subscribe
  }
  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }
}
