dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.1
mail_uid = 1000
mail_gid = 1000
log_path = /dev/stdout
protocols {
  imap = yes
  lmtp = yes
}
mail_plugins {
  mail_crypt = yes
}
ssl = required
ssl_min_protocol = TLSv1.3
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305
ssl_server_prefer_ciphers = server
ssl_server_cert_file = /etc/certificates/fullchain.pem
ssl_server_key_file = /etc/certificates/privkey.pem
auth_username_format = %{user | username | lower}
mail_home = /srv/mail/%{user | username | lower}
passdb file {
  driver = passwd-file
  default_password_scheme=ARGON2ID
  passwd_file_path = /etc/dovecot-local/users
  fields {
    userdb_crypt_user_key_password = %{password | sha512}
  }
}
service auth {
  inet_listener auth {
    port = 500
  }
}
service lmtp {
  inet_listener lmtp {
    port = 24
  }
}
protocol lmtp {
  mail_plugins {
    mail_crypt = yes
    sieve = yes
  }
}
mail_driver = maildir
mail_path = ~/mail
mail_attribute {
  dict file {
    path = ~/mail/attributes
  }
}
crypt_user_key_curve = secp521r1
crypt_user_key_require_encrypted = yes
sieve_script before {
  type = before
  path = /etc/dovecot/default.sieve
}
sieve_script default {
  type = default
  path = /tmp/local.sieve
}
namespace inbox {
  inbox = yes
  mailbox Junk {
    special_use = \Junk
    auto = subscribe
  }
  mailbox Sent {
    special_use = \Sent
    auto = subscribe
  }
  mailbox Trash {
    special_use = \Trash
    auto = subscribe
  }
}
