source_directories:
  - /run/host/etc
  - /run/host/var/home
  - /run/host/var/lib/container-data
  - /run/host/var/lib/containers/storage/secrets
  - /run/host/var/lib/containers/storage/volumes/systemd-*
  - /run/host/var/roothome
repositories:
  - label: remote
    path: ${BORG_REMOTE}
  - label: remote2
    path: ${BORG_REMOTE2}
encryption_passphrase: ${BORG_PASSWORD}
keep_daily: 7
keep_weekly: 4
keep_monthly: 3
read_special: true
loki:
  url: https://metrics.strypsteen.com/loki/api/v1/push
  labels:
    host: __hostname
    job: borgmatic
<<: !include /etc/borgmatic/local.yaml
