source_directories:
  - /run/host/lib/container-data
  - /run/host/lib/containers/storage/secrets
  - /run/host/lib/containers/storage/volumes/systemd-*
  - /run/host/roothome
repositories:
  - label: remote
    path: ${BORG_REMOTE}
  - label: remote2
    path: ${BORG_REMOTE2}
remote_path: borg
encryption_passphrase: ${BORG_PASSWORD}
keep_daily: 7
keep_weekly: 4
read_special: true
exclude_caches: true
<<: !include /etc/borgmatic/local.yaml
