flush ruleset
table inet filter {
  chain forward {
    type filter hook forward priority 0
    policy drop
    ct state established accept
    ct state related accept
    iifname podman* accept
    iifname internal accept
    iifname wifi oifname external accept
    iifname untrusted oifname external accept
  }
}
table ip nat {
  chain postrouting {
    type nat hook postrouting priority 0
    oifname external masquerade
  }
}
