server:
  interface: 0.0.0.0
  interface: ::
  access-control: 192.168.0.0/16 allow
  access-control: fe80::/10 allow
  tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
  trust-anchor-file: /opt/unbound/etc/unbound/var/root.key
forward-zone:
  name: .
  forward-tls-upstream: yes
  forward-addr: 2620:fe::10#dns10.quad9.net
  forward-addr: 9.9.9.10#dns10.quad9.net
include: /opt/unbound/etc/unbound/local.conf
