apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.strypsteen.com/mathieu/atlas
    path: helm
    helm:
      values: |
        image: git.strypsteen.com/infra/atlas
        imageIDE: git.strypsteen.com/infra/atlas-ide
        imagePullSecret: git-strypsteen-com
        namespace: apps
        barmanObjectName: garage-replicated
        apiserverHost: console.strypsteen.com
        webserverHost: console.strypsteen.com
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated: {}
