apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-drivers
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://ceph.github.io/ceph-csi-operator
      chart: ceph-csi-drivers
      targetRevision: 1.0.4
      helm:
        valueFiles:
          - $rook/deploy/charts/ceph-csi-drivers/values.yaml
    - repoURL: https://github.com/rook/rook
      targetRevision: v1.20.3
      ref: rook
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
