apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/squat/generic-device-plugin
    path: manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
