apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
    - namespace: apps
      name: envoy-internal
  hostnames:
    - monitoring.strypsteen.com
  rules:
    - backendRefs:
        - name: prometheus-grafana
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/private-key-algorithm: ECDSA
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: metrics-auth
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - metrics.strypsteen.com
      secretName: metrics-certificate
  rules:
    - host: metrics.strypsteen.com
      http:
        paths:
          - path: /api/v1/write
            pathType: Exact
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
