apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph-cluster
    targetRevision: v1.20.3
    helm:
      values: |
        cephImage:
          tag: v20.2.3
          imagePullPolicy: IfNotPresent
        cephClusterSpec:
          cephConfig:
            global:
              osd_pool_default_size: "2"
          dashboard:
            prometheusEndpoint: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          network:
            connections:
              requireMsgr2: true
              encryption:
                enabled: true
          resources:
            mgr:
              requests:
                cpu: 100m
            mon:
              requests:
                cpu: 100m
            osd:
              requests:
                cpu: 100m
                memory: 1Gi
          storage:
            useAllDevices: false
            storageClassDeviceSets:
              - name: storage
                count: 3
                volumeClaimTemplates:
                  - spec:
                      storageClassName: rook-osd
                      volumeMode: Block
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 400Gi
        cephObjectStores: {}
        cephFileSystems: {}
        cephBlockPools:
          - name: ceph-blockpool
            spec:
              replicated:
                size: 2
            storageClass:
              enabled: true
              name: ceph-block
              allowVolumeExpansion: true
              mountOptions:
                - discard
              parameters:
                csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-publish-secret-namespace: rook-ceph
                csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        toolbox:
          enabled: true
        monitoring:
          enabled: true
          createPrometheusRules: true
        cephBlockPoolsVolumeSnapshotClass:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
