apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-k8s-1
spec:
  storageClassName: rook-osd
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  local:
    path: /dev/mapper/luks2-r-rook
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-1
  capacity:
    storage: 400Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-k8s-2
spec:
  storageClassName: rook-osd
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  local:
    path: /dev/mapper/luks2-r-rook
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-2
  capacity:
    storage: 400Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-k8s-3
spec:
  storageClassName: rook-osd
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  local:
    path: /dev/mapper/luks2-r-rook
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-3
  capacity:
    storage: 400Gi
