apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph-cluster
    targetRevision: v1.18.8
    helm:
      values: |
        cephClusterSpec:
          cephConfig:
            global:
              osd_pool_default_size: "2"
          cephVersion:
            image: quay.io/ceph/ceph:v20.2.0
          monitoring:
            enabled: true
          network:
            connections:
              requireMsgr2: true
              encryption:
                enabled: true
          resources:
            mgr:
              requests:
                cpu: 200m
            mon:
              requests:
                cpu: 200m
            osd:
              requests:
                cpu: 200m
                memory: 2Gi
          storage:
            useAllDevices: false
            storageClassDeviceSets:
              - name: storage
                count: 2
                volumeClaimTemplates:
                  - spec:
                      storageClassName: rook-osd
                      volumeMode: Block
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 400Gi
        cephObjectStores: {}
        cephFileSystems: {}
        toolbox:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
