flush ruleset
table inet filter {
  chain forward {
    type filter hook forward priority 0
    policy drop
    ct state established accept
    ct state related accept
    iifname internal accept
    iifname wifi oifname external accept
    iifname untrusted oifname external accept
    iifname server oifname external accept
    iifname wifi oifname server accept
    iifname untrusted oifname server accept
  }
}
table ip nat {
  chain postrouting {
    type nat hook postrouting priority 0
    oifname external masquerade
  }
}
