flush ruleset
table inet filter {
  chain forward {
    type filter hook forward priority 0
    policy drop
    ct state established accept
    ct state related accept
    iifname podman* accept
    iifname mgmt accept
    iifname internal oifname external accept
    iifname server oifname external accept
    iifname internal oifname server accept
  }
}
table ip nat {
  chain postrouting {
    type nat hook postrouting priority 0
    oifname external masquerade
  }
}
