apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: atlas
spec:
  parentRefs:
    - name: envoy
      sectionName: atlas-api
  rules:
    - backendRefs:
        - name: atlas-api
          port: 8612
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atlas
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - console.strypsteen.com
  rules:
    - backendRefs:
        - name: atlas-web
          port: 8000
      sessionPersistence:
        type: Cookie
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atlas-devproxy
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - "*.dev.console.strypsteen.com"
  rules:
    - backendRefs:
        - name: atlas-devproxy
          port: 8001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atlas-devproxy-proxy
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - "*.devproxy.console.strypsteen.com"
  rules:
    - backendRefs:
        - name: atlas-devproxy
          port: 8001
