apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-static
data:
  Caddyfile: |
    {
      auto_https off
    }
    http://strypsteen.me {
      root /srv
      file_server
      header Content-Security-Policy "default-src 'self'"
      header /.well-known/matrix/client Access-Control-Allow-Origin *
      respond /.well-known/matrix/client <<EOF
      {"m.homeserver": {"base_url": "https://matrix.strypsteen.com"}}
      EOF
      respond /.well-known/matrix/server <<EOF
      {"m.server": "matrix.strypsteen.com:443"}
      EOF
    }
    http://strypsteen.com {
      respond 404
    }
    http://mta-sts.strypsteen.me, http://mta-sts.strypsteen.com {
      respond /.well-known/mta-sts.txt <<EOF
      version: STSv1
      mode: enforce
      mx: vps.strypsteen.com
      max_age: 1209600
      EOF
      respond 404
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <link rel="stylesheet" href="site.css"/>
    </head>
    <body>
      <header>
        <title>Mathieu Strypsteen</title>
        <h1>Mathieu Strypsteen</h1>
      </header>
      <footer>
        <p>
          <a href="mailto:mathieu@strypsteen.me">Mail</a>
          -
          <a href="https://matrix.to/#/@mathieu:strypsteen.me">Matrix</a>
          -
          <a href="https://git.strypsteen.com/mathieu">Git</a>
        </p>
      </footer>
    </body>
    </html>
  site.css: |
    body {
      background-color: #000000;
      color: #fafafafa;
      margin: auto;
      max-width: 1000px;
    }
    header, footer {
      text-align: center;
    }
    a {
      color: #00dbff;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caddy-static
  template:
    metadata:
      name: caddy-static
      labels:
        app: caddy-static
    spec:
      runtimeClassName: gvisor
      volumes:
        - name: config
          configMap:
            name: caddy-static
      containers:
        - name: caddy-static
          image: docker.io/caddy:2.11.2
          volumeMounts:
            - name: config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: config
              mountPath: /srv/index.html
              subPath: index.html
            - name: config
              mountPath: /srv/site.css
              subPath: site.css
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-static
spec:
  selector:
    app: caddy-static
  ports:
    - port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: caddy-static
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - strypsteen.com
    - strypsteen.me
    - mta-sts.strypsteen.com
    - mta-sts.strypsteen.me
  rules:
    - backendRefs:
        - name: caddy-static
          port: 80
