kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hermes
  labels:
    velero-backup: replicated
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      name: hermes
      labels:
        app: hermes
    spec:
      hostUsers: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes
      containers:
        - name: hermes
          image: docker.io/nousresearch/hermes-agent:v2026.8.3
          args: ["gateway", "run"]
          env:
            - name: HERMES_DASHBOARD
              value: "1"
            - name: HERMES_DASHBOARD_PUBLIC_URL
              value: "https://agent.strypsteen.com"
            - name: HERMES_DASHBOARD_OIDC_ISSUER
              value: "https://auth.strypsteen.com/realms/master"
            - name: HERMES_DASHBOARD_OIDC_CLIENT_ID
              value: hermes
            - name: DOCKER_HOST
              value: "tcp://localhost:8888"
          volumeMounts:
            - name: data
              mountPath: /opt/data
        - name: podman
          image: quay.io/podman/stable:v5.8.2
          command: ['bash', '-c', 'rm /etc/containers/containers.conf && rm /home/podman/.config/containers/containers.conf && sudo -u podman -- podman system service -t0 tcp://127.0.0.1:8888']
          securityContext:
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
          resources:
            limits:
              devic.es/tun: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hermes
spec:
  selector:
    app: hermes
  ports:
    - port: 9119
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes
spec:
  parentRefs:
    - name: envoy-internal
  hostnames:
    - agent.strypsteen.com
  rules:
    - backendRefs:
        - name: hermes
          port: 9119
      timeouts:
        request: 600s
