apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: infra
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: infra-vm
    spec:
      domain:
        cpu:
          cores: 4
          model: host-passthrough
        resources:
          requests:
            memory: 4G
        devices:
          disks:
            - name: disk
              disk:
                bus: virtio
            - name: ignition
              disk:
                bus: virtio
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
      volumes:
        - name: disk
          dataVolume:
            name: infra-vm
        - name: ignition
          cloudInitConfigDrive:
            secretRef:
              name: infra-vm
  dataVolumeTemplates:
    - metadata:
        name: infra-vm
      spec:
        storage:
          volumeMode: Block
          resources:
            requests:
              storage: 32Gi
        source:
          registry:
            url: docker://quay.io/fedora/fedora-coreos-kubevirt:stable
---
apiVersion: v1
kind: Service
metadata:
  name: infra-vm
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.31
  selector:
    app: infra-vm
  ports:
    - name: ssh
      port: 22
    - name: http
      port: 80
    - name: https
      port: 443
    - name: forgejo-ssh
      port: 2222
    - name: atlas-api
      port: 8612
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: infra-vm
spec:
  podSelector:
    matchLabels:
      app: infra-vm
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 22
        - port: 80
        - port: 443
        - port: 2222
        - port: 8612
