apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie
  instances: 2
  enablePDB: false
  storage:
    storageClass: local-path
    size: 5Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-replicated
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak-db
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: "0 0 0 * * *"
  cluster:
    name: keycloak-db
  backupOwnerReference: self
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-db
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: keycloak-db
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: keycloak
    - podSelector:
        matchLabels:
          cnpg.io/cluster: keycloak-db
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cnpg-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      runtimeClassName: gvisor
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.6.1-0
          args: ['start', '--hostname=auth.strypsteen.com', '--http-enabled=true', '--proxy-headers=xforwarded', '--db=postgres', '--db-url-host=keycloak-db-rw', '--db-username=app', '--db-url-database=app']
          env:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-app
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - auth.strypsteen.com
  rules:
    - backendRefs:
        - name: keycloak
          port: 8080
