apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        spec:
          hostUsers: false
          restartPolicy: Never
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:42.68.4
              env:
                - name: RENOVATE_PLATFORM
                  value: forgejo
                - name: RENOVATE_ENDPOINT
                  value: https://git.strypsteen.com/api/v1
                - name: RENOVATE_AUTODISCOVER
                  value: 'true'
                - name: RENOVATE_FETCH_CHANGE_LOGS
                  value: 'off'
                - name: RENOVATE_GIT_AUTHOR
                  value: 'Renovate <renovate@strypsteen.me>'
                - name: RENOVATE_PR_HOURLY_LIMIT
                  value: '0'
                - name: RENOVATE_PR_CONCURRENT_LIMIT
                  value: '0'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: token
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: gh-token
