kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden
  labels:
    velero-backup: replicated
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      name: vaultwarden
      labels:
        app: vaultwarden
    spec:
      hostUsers: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden
      containers:
        - name: vaultwarden
          image: ghcr.io/dani-garcia/vaultwarden:1.35.1
          env:
            - name: DOMAIN
              value: https://vault.strypsteen.com
            - name: ICON_SERVICE
              value: bitwarden
            - name: IP_HEADER
              value: X-Forwarded-For
            - name: LOG_LEVEL
              value: warn
            - name: SIGNUPS_ALLOWED
              value: 'false'
            - name: TRASH_AUTO_DELETE_DAYS
              value: '14'
          volumeMounts:
            - name: data
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
    - port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
spec:
  parentRefs:
    - name: envoy
  hostnames:
    - vault.strypsteen.com
  rules:
    - backendRefs:
        - name: vaultwarden
          port: 80
