apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server
data:
  settings.json: |
    {
      "diffEditor.ignoreTrimWhitespace": false,
      "editor.codeLens": false,
      "editor.dragAndDrop": false,
      "editor.folding": false,
      "editor.formatOnPaste": true,
      "editor.formatOnSave": true,
      "editor.formatOnType": true,
      "editor.inlayHints.enabled": "off",
      "editor.multiCursorLimit": 1,
      "editor.selectionClipboard": false,
      "editor.smoothScrolling": true,
      "editor.stickyScroll.enabled": false,
      "editor.tabSize": 2,
      "explorer.confirmDragAndDrop": false,
      "files.autoSave": "off",
      "files.enableTrash": false,
      "files.insertFinalNewline": true,
      "files.trimFinalNewlines": true,
      "files.trimTrailingWhitespace": true,
      "git.confirmSync": false,
      "search.smartCase": true,
      "terminal.integrated.stickyScroll.enabled": false,
      "workbench.colorTheme": "Dark 2026",
      "workbench.editor.empty.hint": "hidden",
      "workbench.localHistory.enabled": false,
      "workbench.settings.enableNaturalLanguageSearch": false,
      "workbench.startupEditor": "none",
      "terminal.integrated.profiles.linux": {
        "bash": {
          "path": "/usr/bin/bash",
          "icon": "terminal-bash"
        }
      },
      "terminal.integrated.defaultProfile.linux": "bash"
    }
