kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server
  labels:
    velero-backup: local
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-nix
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server
data:
  settings.json: |
    {
      "diffEditor.ignoreTrimWhitespace": false,
      "editor.codeLens": false,
      "editor.dragAndDrop": false,
      "editor.folding": false,
      "editor.formatOnPaste": true,
      "editor.formatOnSave": true,
      "editor.formatOnType": true,
      "editor.inlayHints.enabled": "off",
      "editor.multiCursorLimit": 1,
      "editor.selectionClipboard": false,
      "editor.smoothScrolling": true,
      "editor.stickyScroll.enabled": false,
      "editor.tabSize": 2,
      "explorer.confirmDragAndDrop": false,
      "files.autoSave": "off",
      "files.enableTrash": false,
      "files.insertFinalNewline": true,
      "files.trimFinalNewlines": true,
      "files.trimTrailingWhitespace": true,
      "git.confirmSync": false,
      "search.smartCase": true,
      "terminal.integrated.stickyScroll.enabled": false,
      "workbench.colorTheme": "Default Dark Modern",
      "workbench.editor.empty.hint": "hidden",
      "workbench.localHistory.enabled": false,
      "workbench.settings.enableNaturalLanguageSearch": false,
      "workbench.startupEditor": "none"
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      name: code-server
      labels:
        app: code-server
    spec:
      nodeName: k8s-1
      hostUsers: false
      volumes:
        - name: config
          configMap:
            name: code-server
        - name: data
          persistentVolumeClaim:
            claimName: code-server
        - name: nix
          persistentVolumeClaim:
            claimName: code-server-nix
      containers:
        - name: code-server
          image: git.strypsteen.com/infra/code-server
          securityContext:
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
          env:
            - name: PROXY_DOMAIN
              value: code.strypsteen.com
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/coder/.local/share/code-server/Machine/settings.json
              subPath: settings.json
            - name: data
              mountPath: /home/coder/.local/share/code-server
              subPath: code-server
            - name: data
              mountPath: /home/coder/.ssh
              subPath: ssh
            - name: data
              mountPath: /home/coder/projects
              subPath: projects
            - name: nix
              mountPath: /nix
          resources:
            limits:
              squat.ai/fuse: 1
              squat.ai/kvm: 1
              squat.ai/tun: 1
      imagePullSecrets:
        - name: git-strypsteen-com
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  selector:
    app: code-server
  ports:
    - port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: code-server
spec:
  parentRefs:
    - namespace: apps
      name: envoy-internal
  hostnames:
    - code.strypsteen.com
    - "*.code.strypsteen.com"
  rules:
    - backendRefs:
        - name: code-server
          port: 8080
