kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: code-server-sandbox
spec:
  selector:
    matchLabels:
      app: code-server-sandbox
  template:
    metadata:
      name: code-server-sandbox
      labels:
        app: code-server-sandbox
    spec:
      nodeName: k8s-1
      hostUsers: false
      volumes:
        - name: config
          configMap:
            name: code-server
        - name: data
          persistentVolumeClaim:
            claimName: code-server-sandbox
      containers:
        - name: code-server-sandbox
          image: git.strypsteen.com/infra/code-server
          securityContext:
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
          env:
            - name: PROXY_DOMAIN
              value: code-sandbox-proxy.strypsteen.com
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-sandbox
                  key: password
          volumeMounts:
            - name: config
              mountPath: /home/coder/.local/share/code-server/Machine/settings.json
              subPath: settings.json
            - name: data
              mountPath: /home/coder/.local/share/code-server
              subPath: code-server
            - name: data
              mountPath: /home/coder/.ssh
              subPath: ssh
            - name: data
              mountPath: /home/coder/projects
              subPath: projects
          resources:
            limits:
              squat.ai/fuse: 1
              squat.ai/kvm: 1
              squat.ai/tun: 1
      imagePullSecrets:
        - name: git-strypsteen-com
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-sandbox
spec:
  selector:
    app: code-server-sandbox
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-sandbox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - k8s.strypsteen.com
      secretName: k8s-certificate
  rules:
    - host: code-sandbox.strypsteen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server-sandbox
                port:
                  number: 8080
    - host: "*.code-sandbox-proxy.strypsteen.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server-sandbox
                port:
                  number: 8080
