kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: forgejo-runner
spec:
  storageClassName: longhorn-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner
data:
  config.yaml: |
    runner:
      labels: ["debian-13:docker://node:trixie"]
    cache:
      host: host.containers.internal
    container:
      docker_host: "tcp://localhost:8888"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      name: forgejo-runner
      labels:
        app: forgejo-runner
    spec:
      nodeName: k8s-1
      hostUsers: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-runner
        - name: config
          configMap:
            name: forgejo-runner
        - name: containers
          emptyDir: {}
      hostAliases:
        - hostnames:
            - host.containers.internal
          ip: 127.0.0.1
      containers:
        - name: forgejo-runner
          image: code.forgejo.org/forgejo/runner:11.0.0
          command: ['forgejo-runner', 'daemon', '-c', '/etc/forgejo-runner/config.yaml']
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/forgejo-runner/config.yaml
              subPath: config.yaml
        - name: podman
          image: quay.io/podman/stable:v5.6.1
          command: ['bash', '-c', 'rm /etc/containers/containers.conf && rm /home/podman/.config/containers/containers.conf && sudo -u podman -- podman system service -t0 tcp://127.0.0.1:8888']
          securityContext:
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - name: containers
              mountPath: /home/podman/.local/share/containers
          resources:
            limits:
              squat.ai/tun: 1
