kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner
data:
  config.yaml: |
    runner:
      labels: ["debian-12:docker://node:bookworm", "debian-13:docker://node:trixie"]
    container:
      docker_host: "tcp://localhost:8888"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      name: forgejo-runner
      labels:
        app: forgejo-runner
    spec:
      nodeName: k8s-1
      hostUsers: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-runner
        - name: config
          configMap:
            name: forgejo-runner
        - name: containers
          emptyDir: {}
      containers:
        - name: forgejo-runner
          image: code.forgejo.org/forgejo/runner:9.1.1
          command: ['forgejo-runner', 'daemon', '-c', '/etc/forgejo-runner/config.yaml']
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/forgejo-runner/config.yaml
              subPath: config.yaml
        - name: podman
          image: quay.io/podman/stable:v5.5.2
          command: ['podman', 'system', 'service', '-t0', 'tcp://127.0.0.1:8888']
          securityContext:
            runAsUser: 1000
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - name: containers
              mountPath: /home/podman/.local/share/containers
          resources:
            limits:
              squat.ai/tun: 1
