version: v1alpha1
machine:
  install:
    # intel-ucode, realtek-firmware
    image: factory.talos.dev/metal-installer-secureboot/c43979d88ecd7c9881b410e0c5f6c4625062912600a27310ee0db3c98dc4b7fc:v1.12.1
    disk: /dev/nvme0n1
  sysctls:
    kernel.split_lock_mitigate: 0
    user.max_user_namespaces: 10000
  files:
    - path: /etc/cri/conf.d/20-customization.part
      op: create
      content: |
        [plugins]
          [plugins."io.containerd.cri.v1.runtime"]
            device_ownership_from_security_context = true
  kernel:
    modules:
      - name: vfio-pci
      - name: vfio_iommu_type1
cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
    podSubnets:
      - 10.244.0.0/16
      - fd08::/56
    serviceSubnets:
      - 10.96.0.0/12
      - fd09::/112
---
apiVersion: v1alpha1
kind: TimeSyncConfig
bootTimeout: 1m
---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  provider: luks2
  keys:
    - slot: 1
      tpm: {}
      lockToState: true
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: rook
provisioning:
  diskSelector:
    match: system_disk
  minSize: 400GiB
encryption:
  provider: luks2
  keys:
    - slot: 1
      tpm: {}
      lockToState: true
