apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s-2.server.home.arpa
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 500GiB
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: rook
provisioning:
  diskSelector:
    match: system_disk
  minSize: 400GiB
encryption:
  provider: luks2
  keys:
    - slot: 1
      tpm: {}
      lockToState: true
