d /home/coturn 0750 root coturn
d /home/coturn/.local 0755 root root
d /home/coturn/.local/share 0755 root root
d /home/coturn/.local/share/containers 0700 coturn coturn
d /home/podman-mail 0750 root podman-mail
d /home/podman-mail/.local 0755 root root
d /home/podman-mail/.local/share 0755 root root
d /home/podman-mail/.local/share/containers 0700 podman-mail podman-mail
