FROM quay.io/fedora/fedora-toolbox:44
RUN dnf up -y
RUN dnf install -y bash-color-prompt direnv podman netcat nix nix-daemon tini vim-enhanced
RUN dnf install -y https://github.com/coder/code-server/releases/download/v4.132.0/code-server-4.132.0-amd64.rpm
RUN setcap cap_setuid=ep /usr/bin/newuidmap
RUN setcap cap_setgid=ep /usr/bin/newgidmap
RUN useradd coder
COPY subuid /etc/subuid
COPY subuid /etc/subgid
COPY gitconfig /etc/gitconfig
COPY ssh_config /etc/ssh/ssh_config
COPY start.sh /start.sh
USER coder
RUN mkdir -p /home/coder/.local/share
USER root
VOLUME /home/coder/.local/share/containers
RUN chown coder:coder /home/coder/.local/share/containers
CMD ["tini", "/start.sh"]
