FROM quay.io/fedora/fedora-toolbox:42
RUN dnf up -y
RUN dnf install -y bash-color-prompt direnv podman netcat vim-enhanced
RUN dnf install -y https://github.com/coder/code-server/releases/download/v4.103.1/code-server-4.103.1-amd64.rpm
RUN useradd coder
RUN echo "coder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER coder
RUN sh <(curl -L https://nixos.org/nix/install) --no-daemon
COPY nix.conf /home/coder/.config/nix/nix.conf
CMD sudo chown -Rh coder:coder /home/coder; code-server --bind-addr 0.0.0.0:8080 --disable-telemetry --proxy-domain $PROXY_DOMAIN
