FROM ghcr.io/coder/code-server:fedora
RUN mkdir -p /home/coder/.config/systemd/user/default.target.wants
RUN ln -s /etc/systemd/user/code-server.service /home/coder/.config/systemd/user/default.target.wants
USER root
RUN sed /^tsflags/d -i /etc/dnf/dnf.conf
RUN dnf up -y
RUN dnf install -y bash-color-prompt bash-completion cargo hostname hyperfine man-db man-pages nodejs-npm poetry postgresql-server python-unversioned-command rustfmt rust-src systemd-container vim-enhanced
RUN authselect select minimal
RUN mkdir /etc/systemd/system/user@.service.d
RUN mkdir /var/lib/systemd/linger
RUN touch /var/lib/systemd/linger/coder
COPY override.conf /etc/systemd/system/user@.service.d
COPY code-server.service /etc/systemd/user
ENTRYPOINT /sbin/init
