FROM quay.io/fedora/fedora-toolbox:42
RUN dnf up -y
RUN dnf install -y bash-color-prompt libglvnd-gles libglvnd-opengl netcat systemd-container vim-enhanced xdg-desktop-portal-gtk xdg-utils
RUN useradd mathieu
RUN echo "mathieu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo WAYLAND_DISPLAY=/run/wayland-0 >> /etc/environment
RUN echo PIPEWIRE_RUNTIME_DIR=/run >> /etc/environment
RUN echo XDG_CURRENT_DESKTOP=GNOME >> /etc/environment
USER mathieu
RUN sh <(curl -L https://nixos.org/nix/install) --no-daemon
USER root
ENTRYPOINT /sbin/init
