d /home/gitea 0750 root gitea
d /home/gitea/.local 0755 root root
d /home/gitea/.local/share 0755 root root
d /home/gitea/.local/share/containers 0700 gitea gitea
d /home/monero 0750 root monero
d /home/monero/.local 0755 root root
d /home/monero/.local/share 0755 root root
d /home/monero/.local/share/containers 0700 monero monero
d /home/synapse 0750 root synapse
d /home/synapse/.local 0755 root root
d /home/synapse/.local/share 0755 root root
d /home/synapse/.local/share/containers 0700 synapse synapse
d /home/vaultwarden 0750 root vaultwarden
d /home/vaultwarden/.local 0755 root root
d /home/vaultwarden/.local/share 0755 root root
d /home/vaultwarden/.local/share/containers 0700 vaultwarden vaultwarden
