[Resolve]
DNS=2620:fe::10#dns10.quad9.net 9.9.9.10#dns10.quad9.net
FallbackDNS=
DNSSEC=true
DNSOverTLS=true
DNSStubListenerExtra=192.168.255.1
DNSStubListenerExtra=192.168.254.1
DNSStubListenerExtra=192.168.253.1
DNSStubListenerExtra=192.168.252.1
