FROM registry.access.redhat.com/ubi10
RUN dnf install -y git nodejs22
RUN curl -L https://github.com/enricoros/big-AGI/archive/refs/heads/v2-dev.tar.gz | tar xz && mv big-AGI-* big-agi
WORKDIR big-agi
ENV NEXT_TELEMETRY_DISABLED 1
RUN mv middleware_BASIC_AUTH.ts middleware.ts
RUN npm ci
RUN npm run build
CMD ["npx", "next", "start"]
