FROM registry.access.redhat.com/ubi9 AS builder
RUN curl -L https://github.com/enricoros/big-AGI/archive/refs/heads/v2-dev.tar.gz | tar xz && mv big-AGI-* big-AGI
FROM registry.access.redhat.com/ubi9/nodejs-20-minimal
ENV NEXT_TELEMETRY_DISABLED 1
COPY --from=builder /big-AGI .
RUN mv middleware_BASIC_AUTH.ts middleware.ts
RUN npm ci
RUN npm run build
CMD npx next start
