interface=wifi
driver=nl80211
ssid=wifi
country_code=BE
ieee80211d=1
ieee80211h=1
hw_mode=a
channel=36
preamble=1
auth_algs=1
wmm_enabled=1
ap_isolate=1
multicast_to_unicast=1
ieee80211n=1
ht_capab=[LDPC][HT40-][HT40+][GF][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][DSSS_CCK-40]
require_ht=1
ieee80211ac=1
vht_capab=[RXLDPC][SHORT-GI-80][TX-STBC-2BY1][RX-STBC-1][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]
require_vht=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=GCMP-256 CCMP
ieee80211w=2
beacon_prot=1

sae_password=REPLACEME
