#!/bin/bash
# shellcheck disable=1091
mesg n
. /etc/environment
export VIMINIT
unset HISTFILE
export LESSHISTFILE=-
if [[ $- != *i* ]]; then
  return
fi
if [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
fi
alias ls="ls --color=auto"
alias grep="grep --color=auto"
